language: python
python:
    - 2.7
install: 
    - python setup.py install
    - pip install -r requirements.txt --use-mirrors
    - pip install -r tests/requirements.txt --use-mirrors
notifications:
  email: false