language: python
python:
    - 2.7
install: 
    - python setup.py install
    - pip install -r requirements.txt --use-mirrors
    - pip install -r tests/requirements.txt --use-mirrors
	- pip install coveralls --use-mirrors
script:
	- coverage run --source=tz setup.py test
notifications:
  email: false
after_success:
  - coveralls  